{
 "title": "OP Stack P2P",
 "tags": [ "op-stack" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "op_node_default_up" } }
  ]
 },
 "panels": [
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_p2p_peer_count{stack_optimism_io_network=\"$network\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Peers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "op_node_default_p2p_peer_count{stack_optimism_io_network=\"$network\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Gossip Events/s [5m]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_gossip_events_total{stack_optimism_io_network=\"$network\"}[5m])",
     "legendFormat": "{{namespace}} - {{type}}"
    }
   ]
  },
  {
   "title": "Bandwidth In [5m]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_bandwidth_bytes_total{stack_optimism_io_network=\"$network\", direction=\"in\"}[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bandwidth Out [5m]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_bandwidth_bytes_total{stack_optimism_io_network=\"$network\", direction=\"out\"}[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}