{
 "title": "OP Stack op-node Rollup Events",
 "tags": [ "op-stack" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(op_node_default_up,stack_optimism_io_network)"
    }
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(op_node_default_up{stack_optimism_io_network=\"$network\"},namespace)"
    }
   },
   {
    "name": "deriver",
    "label": "Deriver",
    "query": {
     "query": "label_values(op_node_default_events_processed{stack_optimism_io_network=\"$network\", namespace=~\"$node\"},deriver)"
    }
   },
   {
    "name": "emitter",
    "label": "emitter",
    "query": {
     "query": "label_values(op_node_default_events_emitted{stack_optimism_io_network=\"$network\", namespace=~\"$node\"},emitter)"
    }
   },
   {
    "name": "event_type",
    "label": "Event Type",
    "query": {
     "query": "label_values(op_node_default_events_emitted{stack_optimism_io_network=\"$network\", namespace=~\"$node\"},event_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Events processed per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_processed{stack_optimism_io_network=\"$network\",namespace=\"$node\",deriver=~\"$deriver\",event_type=~\"$event_type\"}[$__rate_interval])",
     "legendFormat": "{{deriver}} {{event_type}}"
    }
   ]
  },
  {
   "title": "Processing time / real time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_process_time{stack_optimism_io_network=\"$network\",namespace=\"$node\",deriver=~\"$deriver\",event_type=~\"$event_type\"}[$__rate_interval])",
     "legendFormat": "{{deriver}} {{event_type}}"
    }
   ]
  },
  {
   "title": "Processing time / real time, by Deriver",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_process_time{stack_optimism_io_network=\"$network\",namespace=\"$node\",deriver=~\"$deriver\",event_type=~\"$event_type\"}[$__rate_interval])) by (deriver)",
     "legendFormat": "{{deriver}}"
    }
   ]
  },
  {
   "title": "Events emitted per second, by Emitter",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_emitted{stack_optimism_io_network=\"$network\",namespace=\"$node\",emitter=~\"$emitter\",event_type=~\"$event_type\"}[$__rate_interval])) by (emitter)",
     "legendFormat": "{{emitter}}"
    }
   ]
  },
  {
   "title": "Events emitted per second, by Event-type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_emitted{stack_optimism_io_network=\"$network\",namespace=\"$node\",emitter=~\"$emitter\",event_type=~\"$event_type\"}[$__rate_interval])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}